---
name: '💬 Question'
description: Ask questions about the project / 提问关于项目的问题
title: '[Ques]: '
labels: ['status: waiting for maintainer']
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the Question / 问题描述
      placeholder: |
        Please provide a clear and concise description of the question you have. / 请提供清晰简洁的问题描述。
        Include any relevant context or details that might help in understanding your question. / 包含任何可能有助于理解您问题的相关背景或细节。

---


